# Generated by Django 6.0.4 on 2026-05-05 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expensesApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, default='broken-coin.png', null=True, upload_to=''),
        ),
    ]
