# Generated by Django 6.0.4 on 2026-05-05 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expensesApp', '0002_alter_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, default='activity.svg', null=True, upload_to=''),
        ),
    ]
