# Generated by Django 6.0.5 on 2026-05-06 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expensesApp', '0003_alter_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, default='anchor.png', null=True, upload_to=''),
        ),
    ]
